export const appendixCopy = {
  zh: {
    eyebrow: '附录 · 不先计算步数',
    title: '为什么恰好用这些步完成的走法确实存在？',
    alternativeTitle: '另一种更直接的证明：这套搬法能达到下界',
    alternativeText: '前一页通过比较两个数列的起点和递推关系，证明构造走法的步数等于下界。这里直接从搬法出发：小塔能达到下界，就能构造出大塔达到下界的走法。',
    shortestPageLabel: '“还能更少吗？”',
    intro: '[[shortest]]已经讨论了两个盘和三个盘的步数下界。这里把论证推广到每个盘数，不先计算具体步数，直接证明这套搬法最省步数。',
    routeTitle: '先说清这套搬法',
    routeIntro: '只有一个盘，就直接移到目标柱。盘数更多时，反复使用下面三步；每次搬小塔，三根柱子的角色可以改变。',
    routeSteps: [
      '按同一套搬法把最大盘上方的小塔搬到临时柱。',
      '把最大盘搬到目标柱。',
      '再按同一套搬法把小塔搬到目标柱，叠在最大盘上。',
    ],
    base: '只有一个盘时，一步就能搬完，也不可能少于一步。',
    proofLabel: '证明',
    let: '设 n 是一个整数。',
    assumptionLead: '假设',
    assumption: '按刚描述的搬法，n 个盘已经能用最少步数搬完。',
    extension: '柱子的名字不改变移动规则，所以下面两次搬小塔都能使用假设中的最省步数走法。现在在这座塔下面加一个最大盘。',
    steps: [
      '按刚描述的搬法，把上面 n 个盘的小塔从 A 搬到 B，留出 C。根据假设，这一段已经用最少步数。',
      '把新最大盘从 A 移到 C。',
      '再按刚描述的搬法，把小塔从 B 搬到 C。这次 B 是起始柱，A 是临时柱，C 是目标柱；根据假设，这一段也用最少步数。',
    ],
    resultLead: '这样',
    result: '，这套搬法对 n+1 个盘所用的步数，就是两次搬 n 个盘的最少步数，再加中间的一步。最大盘第一次移动前，小塔必须完整搬到另一根柱；最大盘最后到达目标柱后，小塔还得完整搬到目标柱。每种走法都省不掉这两段搬运，以及中间最大盘至少一次移动。因此，这套搬法也用最少步数搬完 n+1 个盘。',
    implicationLead: '所以',
    implication: '，对于这个 n，只要这套搬法能用最少步数搬完 n 个盘，就能用最少步数搬完 n+1 个盘。',
    conclusion: '综上，对于每个正整数 m，这套搬法都能用最少步数搬完 m 个盘。因此，相应的步数下界确实能达到。',
    proofEnd: '证明完毕',
    back: '返回说明理由',
    restart: '重新体验',
  },
  en: {
    eyebrow: 'APPENDIX · WITHOUT COUNTING THE MOVES FIRST',
    title: 'Why does a route achieving this bound exist?',
    alternativeTitle: 'A more direct alternative proof: this method achieves the bound',
    alternativeText: 'The preceding page compares the starting values and recurrences of two sequences to show that the constructed route achieves the bound. Here we reason directly about the method: a smaller-tower route that achieves the bound lets us construct one for the larger tower.',
    shortestPageLabel: 'SHORTEST?',
    intro: '[[shortest]] discussed lower bounds for two and three discs. Here we extend the argument to every disc count and prove that this method is shortest without first calculating its move count.',
    routeTitle: 'Describe the method',
    routeIntro: 'With one disc, move it directly to the target. With more discs, repeat the three steps below; the pegs can change roles during each smaller-tower transfer.',
    routeSteps: [
      'Use this same method to transfer the smaller tower above the largest disc to the temporary peg.',
      'Move the largest disc to the target peg.',
      'Use the same method again to transfer the smaller tower onto the largest disc.',
    ],
    base: 'With one disc, a single move finishes the task, and fewer than one move is impossible.',
    proofLabel: 'Proof',
    let: 'Let n be an integer.',
    assumptionLead: 'Assume',
    assumption: 'this method finishes an n-disc tower in the fewest possible moves.',
    extension: 'Changing the peg names does not change the movement rules, so the shortest n-disc method can be used in both smaller-tower transfers. Now add a new largest disc underneath.',
    steps: [
      'Use this method to transfer the upper n-disc tower from A to B, leaving C empty. By the assumption, this transfer uses the fewest moves.',
      'Move the new largest disc from A to C.',
      'Use the same method to transfer the smaller tower from B to C. B is now the start, A the temporary peg and C the target. By the assumption, this transfer also uses the fewest moves.',
    ],
    resultLead: 'Thus',
    result: ', this method uses two shortest n-disc transfers plus one move for an n + 1-disc tower. Before the largest disc first moves, the smaller tower must be transferred to another peg. After the largest disc last arrives at the target, the smaller tower must still be transferred onto it. Every route requires these two transfers and at least one move of the largest disc between them. This method therefore also finishes n + 1 discs in the fewest moves.',
    implicationLead: 'So',
    implication: ', for this n, if this method is shortest for n discs, it is shortest for n + 1 discs.',
    conclusion: 'Therefore, for every positive integer m, this method finishes m discs in the fewest moves. The corresponding lower bound is therefore achievable.',
    proofEnd: 'End of proof',
    back: 'Back to the proof',
    restart: 'Restart experience',
  },
}
