export const appendixCopy = {
  zh: {
    eyebrow: '附录 · 不先计算步数',
    title: '为什么恰好用这些步完成的走法确实存在？',
    shortestPageLabel: '“还能更少吗？”',
    intro: '前面已经说明不能用更少的步数完成。这里不先算出具体步数，而是证明这套搬法确实能达到下界。',
    routeTitle: '先说清这套搬法',
    routeIntro: '只有一个盘，就直接移到目标柱。盘数更多时，反复使用下面三步；每次搬小塔，三根柱子的角色可以改变。',
    routeSteps: [
      '按同一套搬法把最大盘上方的小塔搬到临时柱。',
      '把最大盘搬到目标柱。',
      '再按同一套搬法把小塔搬到目标柱，叠在最大盘上。',
    ],
    base: '只有一个盘时，一步就能搬完，也不可能少于一步。',
    proofLabel: '证明',
    let: '设 n 是一个整数。',
    assumptionLead: '假设',
    assumption: '按刚描述的搬法，n 个盘已经能用最少步数搬完。',
    extension: '柱子的名字不改变移动规则，所以下面两次搬小塔都能使用假设中的最省步数走法。现在在这座塔下面加一个最大盘。',
    steps: [
      '按刚描述的搬法，把上面 n 个盘的小塔从 A 搬到 B，留出 C。根据假设，这一段已经用最少步数。',
      '把新最大盘从 A 移到 C。',
      '再按刚描述的搬法，把小塔从 B 搬到 C。这次 B 是起始柱，A 是临时柱，C 是目标柱；根据假设，这一段也用最少步数。',
    ],
    resultLead: '这样',
    result: '，这套搬法对 n+1 个盘所用的步数，就是两次搬 n 个盘的最少步数，再加中间的一步。[[shortest]]中的下界理由表明：别的走法省不掉这前后两段和中间一步。因此，这套搬法也用最少步数搬完 n+1 个盘。',
    implicationLead: '所以',
    implication: '，对于这个 n，只要这套搬法能用最少步数搬完 n 个盘，就能用最少步数搬完 n+1 个盘。',
    conclusion: '综上，对于每个正整数 m，这套搬法都能用最少步数搬完 m 个盘。[[shortest]]讨论的步数下界，确实存在走法恰好达到。',
    proofEnd: '证明完毕',
    back: '返回说明理由',
    restart: '重新体验',
  },
  en: {
    eyebrow: 'APPENDIX · WITHOUT COUNTING THE MOVES FIRST',
    title: 'Why does a route achieving this bound exist?',
    shortestPageLabel: 'SHORTEST?',
    intro: 'We have shown that fewer moves cannot work. Without calculating the exact count first, prove that this method reaches the bound.',
    routeTitle: 'Describe the method',
    routeIntro: 'With one disc, move it directly to the target. With more discs, repeat the three steps below; the pegs can change roles during each smaller-tower transfer.',
    routeSteps: [
      'Use this same method to transfer the smaller tower above the largest disc to the temporary peg.',
      'Move the largest disc to the target peg.',
      'Use the same method again to transfer the smaller tower onto the largest disc.',
    ],
    base: 'With one disc, a single move finishes the task, and fewer than one move is impossible.',
    proofLabel: 'Proof',
    let: 'Let n be an integer.',
    assumptionLead: 'Assume',
    assumption: 'this method finishes an n-disc tower in the fewest possible moves.',
    extension: 'Changing the peg names does not change the movement rules, so the shortest n-disc method can be used in both smaller-tower transfers. Now add a new largest disc underneath.',
    steps: [
      'Use this method to transfer the upper n-disc tower from A to B, leaving C empty. By the assumption, this transfer uses the fewest moves.',
      'Move the new largest disc from A to C.',
      'Use the same method to transfer the smaller tower from B to C. B is now the start, A the temporary peg and C the target. By the assumption, this transfer also uses the fewest moves.',
    ],
    resultLead: 'Thus',
    result: ', this method uses two shortest n-disc transfers plus one move for an n + 1-disc tower. The lower-bound argument on [[shortest]] shows that no route can avoid these two transfers and the move between them. This method therefore also finishes n + 1 discs in the fewest moves.',
    implicationLead: 'So',
    implication: ', for this n, if this method is shortest for n discs, it is shortest for n + 1 discs.',
    conclusion: 'Therefore, for every positive integer m, this method finishes m discs in the fewest moves. A route really does achieve the bound discussed on [[shortest]].',
    proofEnd: 'End of proof',
    back: 'Back to the proof',
    restart: 'Restart experience',
  },
}
