export const discCountsCopy = {
  zh: {
    eyebrow: '拆解步骤 · 对照理由',
    heading: '把刚才构造的走法演示出来',
    intro: '刚才已经说明，已有的小塔搬法可以前后各用一遍，中间移动最大盘。现在用四个盘对照这个构造：同一个小盘前后各动了几次？先说清理由，再用演示核对。',
    title: '每个圆盘已经移动几次？',
    note: '从大到小排列，只记录已经发生的移动。',
    labels: ['最大圆盘', '第二大', '第三大', '最小圆盘'],
    only: '唯一的圆盘',
    smallest: '最小圆盘',
    unit: () => '次',
    total: '合计步数',
    teacher: '先让学生回想刚才构造走法的方法：两次小塔搬运都用已有方法，同一个盘的次数怎样合起来？学生说明后，再步进核对。四盘演示在第七、八步暂停，用逐盘计数把每个盘与和式中的一项对应起来。下一页继续说明为什么别的走法不能更少。',
    sumNote: '这个和式按圆盘从大到小排列：第一项数最大圆盘的移动次数，接着数第二大圆盘，再依次往下数。它描述的是演示路线走完后的次数。',
    next: '把理由连起来',
    connection: '这套走法已经构造出来，计数也对上了。下一页继续解释：为什么换一种走法，也不能让总步数更少？',
    status: { playing: '对照刚才的理由', paused: '停下来说明理由', exploring: '你的实际走法' },
    pause: {
      start: ['先回想刚才的构造', '用已有方法把小塔移开，移动最大盘，再用已有方法把小塔搬到 C。两遍都用同一个搬法，同一个小盘的次数怎样合起来？说清后，再开始演示。'],
      one: ['从一个圆盘开始', '只有这个圆盘需要移动。从 A 移到 C，一步就完成。先说出理由，再演示这一步。'],
      before: ['第一遍搬完，最大圆盘才能动', '上面的小塔已完整移开，C 也空出来了。这正对应刚才想清楚的第一遍搬运：小塔里的每个圆盘，先完成自己这一遍的移动。'],
      after: ['接下来是同一座小塔的第二遍搬运', '最大圆盘已到 C，但整座塔还没搬完。小塔仍要完整搬到 C，再用一遍已经想清楚的搬法；同一个小圆盘的次数还要再算一遍。'],
      second: ['用同一个搬法完成第二遍', '柱子的角色换了，小塔内部的搬法没变。每个小圆盘重复自己在第一遍中的移动次数，计数与这段理由逐步对应。'],
      complete: ['每一项都对应一个圆盘', '最大圆盘移动一次；每个小圆盘把前后两遍的次数相加。用这个理由说明下面的计数，再展开和式，把每一项与它所数的圆盘对应起来。'],
      oneComplete: ['一个圆盘，移动一次', '这个圆盘已经到达 C。总步数就是它自己的移动次数。'],
      exploring: ['继续记录你的走法', '下面的次数会跟着你的实际移动更新。折叠区里的和式描述演示路线；点击“重新开始演示”可以回到那条路线。'],
      exploredComplete: ['你的走法已经完成', '先比较每个圆盘的实际次数。折叠区里的和式描述演示路线，未必与你这次的次数相同。'],
    },
  },
  en: {
    eyebrow: 'STEPS · PLAY THROUGH THE REASONING',
    heading: 'Play through the method we constructed',
    intro: 'We have established a construction: use the smaller-tower method twice, with one largest-disc move between them. Use four discs to connect this construction to each disc’s moves. Explain how its two counts combine before checking the walkthrough.',
    title: 'How many times has each disc moved?',
    note: 'Largest to smallest. These are moves made so far.',
    labels: ['Largest disc', 'Second largest', 'Third largest', 'Smallest disc'],
    only: 'Only disc',
    smallest: 'Smallest disc',
    unit: (value) => value === 1 ? 'move' : 'moves',
    total: 'Total moves',
    teacher: 'Recall the method just constructed. If both smaller transfers use the existing method, how do the two counts for the same disc combine? Explain before checking the moves. The four-disc walkthrough pauses after moves seven and eight; the counters connect each disc to a term in the sum. The next page explains why another route cannot use fewer moves.',
    sumNote: 'Read this sum from the largest disc to the smallest. The first term counts the largest disc, the next counts the second largest, and so on. These are the counts at the end of the demonstrated route.',
    next: 'Connect the reasoning',
    connection: 'We have constructed the route and accounted for its moves. Next, explain why a different route cannot use fewer moves.',
    status: { playing: 'CONNECT THE MOVES WITH YOUR REASONING', paused: 'PAUSE & EXPLAIN', exploring: 'YOUR ACTUAL ROUTE' },
    pause: {
      start: ['Recall the construction', 'Use the existing method to move the smaller tower away, move the largest disc, then use the method again to transfer the smaller tower to C. How do the two counts for the same disc combine? Explain before starting the walkthrough.'],
      one: ['Start with one disc', 'Only this disc needs to move. One move from A to C finishes the task. Explain why, then play through that move.'],
      before: ['The first transfer frees the largest disc', 'The smaller tower has moved away completely, leaving C empty. This is the first transfer you reasoned through: each smaller disc has completed its part in that transfer.'],
      after: ['The same smaller tower must move again', 'The largest disc has reached C, but the full tower is unfinished. Transfer the smaller tower to C using the method already understood. The same smaller disc’s moves must be counted again.'],
      second: ['Use the same method for the second transfer', 'The peg roles have changed, but the smaller-tower method has not. Each smaller disc repeats its own move count from the first transfer. The counters connect each move with this reasoning.'],
      complete: ['Each term counts one disc', 'The largest disc moved once. Each smaller disc combines its counts from the two transfers. Use this reasoning to explain the counters, then open the sum and match each term to its disc.'],
      oneComplete: ['One disc, one move', 'The disc has reached C. Its own move count is the total.' ],
      exploring: ['Keep counting your route', 'The counters follow your actual moves. The folded sum describes the demonstrated route. Select Restart walkthrough to return to that route.'],
      exploredComplete: ['Your route is complete', 'Compare the actual counts for each disc. The folded sum describes the demonstrated route, so its counts may differ from yours.'],
    },
  },
}
