export const discCountsCopy = {
  zh: {
    eyebrow: '拆解步骤 · 对照理由',
    heading: '把刚才构造的走法演示出来',
    intro: '先用四个盘演示构造走法，再核对它实际用了多少步。',
    provisionalTitle: '我们将在下一页揭晓',
    provisionalNote: '前面讨论的步数下界，能否被达到？',
    focusCue: '先别从几个总步数里猜规律。看着眼前这条走法，除了从头到尾数步骤，还能怎样整理这些移动？',
    openCount: '先想好，再展开核对',
    title: '每个圆盘已经移动几次？',
    note: '从大到小排列，只记录已经发生的移动。',
    labels: ['最大圆盘', '第二大', '第三大', '最小圆盘'],
    only: '唯一的圆盘',
    smallest: '最小圆盘',
    unit: () => '次',
    total: '合计步数',
    teacher: '先让学生回想刚才构造走法的方法：两次小塔搬运都用已有方法，同一个盘的次数怎样合起来？学生说明后，再步进核对。四盘演示在第七、八步暂停，用逐盘计数把每个盘与和式中的一项对应起来。下一页继续说明为什么别的走法不能更少。',
    next: '把理由连起来',
    status: { playing: '对照刚才的理由', paused: '停下来说明理由', exploring: '你的实际走法' },
    pause: {
      start: ['先想怎样计数', '开始演示前，先说说你打算怎样计算这条走法的总步数。'],
      one: ['从一个圆盘开始', '只有这个圆盘需要移动。从 A 移到 C，一步就完成。先说出理由，再演示这一步。'],
      before: ['最大圆盘即将移动', '上面的小塔已完整移开，C 也空出来了。先说明这一步为什么现在可以走。'],
      after: ['塔还没有搬完', '最大圆盘已到 C。接下来要搬哪一部分？与刚才的做法有什么关系？'],
      second: ['继续完成这条走法', '继续观察，核对你刚才关于步数的想法。'],
      complete: ['这条走法已经完成', '先解释你打算怎样重新数这些移动，再展开计数核对。'],
      oneComplete: ['一个圆盘，移动一次', '这个圆盘已经到达 C。总步数就是它自己的移动次数。'],
      exploring: ['继续记录你的走法', '展开后可以核对你实际完成的移动；和式描述原先演示的路线。点击“重新开始演示”可以回到那条路线。'],
      exploredComplete: ['你的走法已经完成', '先想怎样整理刚才的移动，再展开核对。和式描述原先演示的路线，未必与你这次的步数相同。'],
    },
  },
  en: {
    eyebrow: 'STEPS · PLAY THROUGH THE REASONING',
    heading: 'Play through the method we constructed',
    intro: 'Play through the constructed four-disc route, then check how many moves it actually uses.',
    provisionalTitle: 'We’ll reveal the answer on the next page',
    provisionalNote: 'Can the move lower bound discussed earlier be achieved?',
    focusCue: 'Do not rush to guess a pattern from a few totals. Looking at this route, how else could you organise its moves besides counting them in order?',
    openCount: 'Think first, then open the count',
    title: 'How many times has each disc moved?',
    note: 'Largest to smallest. These are moves made so far.',
    labels: ['Largest disc', 'Second largest', 'Third largest', 'Smallest disc'],
    only: 'Only disc',
    smallest: 'Smallest disc',
    unit: (value) => value === 1 ? 'move' : 'moves',
    total: 'Total moves',
    teacher: 'Recall the method just constructed. If both smaller transfers use the existing method, how do the two counts for the same disc combine? Explain before checking the moves. The four-disc walkthrough pauses after moves seven and eight; the counters connect each disc to a term in the sum. The next page explains why another route cannot use fewer moves.',
    next: 'Connect the reasoning',
    status: { playing: 'CONNECT THE MOVES WITH YOUR REASONING', paused: 'PAUSE & EXPLAIN', exploring: 'YOUR ACTUAL ROUTE' },
    pause: {
      start: ['Plan how to count', 'Before starting the walkthrough, explain how you plan to calculate its total moves.'],
      one: ['Start with one disc', 'Only this disc needs to move. One move from A to C finishes the task. Explain why, then play through that move.'],
      before: ['The largest disc can move next', 'The smaller tower has moved away and C is empty. Explain why this move is now possible.'],
      after: ['The tower is not finished yet', 'The largest disc is on C. Which part must move next, and how does that relate to the earlier method?'],
      second: ['Continue the route', 'Keep watching and check the way you planned to account for its moves.'],
      complete: ['The route is complete', 'Explain how you would count these moves another way, then open the count to check.'],
      oneComplete: ['One disc, one move', 'The disc has reached C. Its own move count is the total.' ],
      exploring: ['Keep tracking your route', 'Open the count to check the moves you actually made. The sum describes the demonstrated route. Select Restart walkthrough to return to that route.'],
      exploredComplete: ['Your route is complete', 'First consider how to organise the moves you made, then open the count to check. The sum describes the demonstrated route, so its total may differ from yours.'],
    },
  },
}
