export const existenceCopy = {
  zh: {
    title: '继续加盘，也一定能搬完吗？',
    intro: '三个盘能搬完，是因为我们已经把走法一步步做出来了。可我们不能把每种盘数都试一遍：会不会加到某个数量，就没有走法了？',
    lead: '先想两次“多一个盘”：已会搬 2 个盘，怎样借此搬 2+1 个盘？已会搬 3 个盘，怎样借此搬 3+1 个盘？',
    leadQuestion: '这两次的做法有什么相同之处？如果继续加盘，刚才的想法还能用吗？',
    diagramCaptions: ['先把上面五个盘搬到 B，留出 C', '把最大盘从 A 移到 C', '再把五个小盘从 B 搬到 C'],
    reveal: '先想一想，再展开证明',
    startTitle: '从一个盘开始',
    start: '一个盘直接移到目标柱，就搬完了。',
    stepTitle: '已有的走法，怎样帮助我们多搬一个盘？',
    setup: '设 n 是大于 1 的整数。如果已经会把 n − 1 个盘搬到另一根柱上，现在在下面加一个最大盘。',
    steps: [
      '用已有的方法，把上面的小塔从 A 搬到 B，留出 C。',
      '把最大盘从 A 移到 C。',
      '再用已有的方法，把小塔从 B 搬到 C。这次 B 是起始柱，A 是临时柱，C 是目标柱；C 底下的大盘不会妨碍小盘移动。',
    ],
    implication: '只要 n − 1 个盘有走法，n 个盘就也有走法。',
    conclusion: '一个盘已经有走法。用刚才的方法，就能构造出两个盘的走法，再构造三个盘的走法，继续往下做。对于每个正整数 n，从一个盘开始接着构造 n − 1 次，就能得到 n 个盘的走法。',
    noException: '不会加到某个盘数就突然失败：起点已经能做到，而且每增加一个盘，都有继续下去的方法。',
    name: '这就是数学归纳法：先说明起点能做到，再说明怎样从少一个盘的走法构造出多一个盘的走法。',
    next: '现在我们知道碟子继续增加也有走法。下一页再问：能不能走得更少？',
    teacher: '先请学生说明两次小塔搬运各自怎样使用已有方法，再展开核对。听他们能否解释柱子的角色变化。等起点与增加一个盘的方法都讲清楚，再介绍“数学归纳法”这个名字。此处先证明有解，随后再讨论这套方法的步数。',
  },
  en: {
    title: 'Can we always finish as we add more discs?',
    intro: 'We know three discs can be moved because we have built a route step by step. But we cannot try every disc count. Could there be a count with no route at all?',
    lead: 'Think about adding one disc twice: if you can move 2 discs, how could that route help you move 2 + 1 discs? If you can move 3 discs, how could it help you move 3 + 1 discs?',
    leadQuestion: 'What is the same in both methods? Could the same idea work as you keep adding discs?',
    diagramCaptions: ['Move the five smaller discs to B, leaving C empty', 'Move the largest disc from A to C', 'Move the five smaller discs from B to C'],
    reveal: 'Think it through, then open the proof',
    startTitle: 'Start with one disc',
    start: 'Move the single disc directly to the target. The task is complete.',
    stepTitle: 'How does an existing method let us move one more disc?',
    setup: 'Let n be an integer greater than 1. If we already have a method for moving n − 1 discs to another peg, add a new largest disc underneath.',
    steps: [
      'Use the existing method to move the smaller tower from A to B, leaving C empty.',
      'Move the largest disc from A to C.',
      'Use the existing method again to move the smaller tower from B to C. B is now the start, A the temporary peg and C the target. The larger disc underneath on C does not obstruct the smaller discs.',
    ],
    implication: 'If n − 1 discs have a route, then n discs have a route too.',
    conclusion: 'One disc already has a route. The construction gives a route for two discs, then three, and continues. For every positive integer n, starting with one disc and applying the construction n − 1 times gives a route for n discs.',
    noException: 'There is no disc count at which this suddenly fails: the starting case works, and each added disc has a way to continue.',
    name: 'This is mathematical induction: establish the starting case, then explain how a route for one fewer disc gives a route for one more.',
    next: 'We now know that a route exists as the number of discs grows. Next, ask whether fewer moves could work.',
    teacher: 'Ask how each smaller-tower transfer uses the existing method before opening the proof. Listen for an explanation of the changing peg roles. Introduce the name “mathematical induction” after the starting case and the extension are clear. Establish existence here, then discuss the method’s move count.',
  },
}
