export const existenceCopy = {
  zh: {
    title: '继续加盘，也一定能搬完吗？',
    intro: '三个盘能搬完，是因为我们已经把走法一步步做出来了。可我们不能把每种盘数都试一遍：会不会加到某个数量，就没有走法了？',
    lead: '先想两次“多一个盘”：已会搬 2 个盘，怎样借此搬 2+1 个盘？已会搬 3 个盘，怎样借此搬 3+1 个盘？',
    leadQuestion: '这两次的做法有什么相同之处？如果继续加盘，刚才的想法还能用吗？',
    diagramCaptions: ['先把上面五个盘搬到 B，留出 C', '把最大盘从 A 移到 C', '再把五个小盘从 B 搬到 C'],
    reveal: '先想一想，再展开证明',
    startTitle: '再看起点：一个盘',
    start: '一个盘直接移到目标柱，就有走法。',
    stepTitle: '从 n 个盘走到 n+1 个盘',
    setup: '设 n 是正整数。假设已经有把 n 个盘从一根柱搬到另一根柱的走法。现在在这 n 个盘下面加一个更大的盘，得到 n+1 个盘。',
    steps: [
      '用已有的方法，把上面 n 个盘从 A 搬到 B，此时 C 仍空着。',
      '把最大盘从 A 移到 C。',
      '再用已有的方法，把 n 个盘从 B 搬到 C。这次 B 是起始柱，A 是临时柱，C 是目标柱；C 底下的大盘不会妨碍小盘移动。',
    ],
    implication: '只要 n 个盘有走法，就能照此构造出 n+1 个盘的走法。',
    conclusion: '从一个盘开始，每次增加一个盘，走法都能接着构造下去。因此，对于每个正整数 n，都能把 n 个盘按规则搬到目标柱。',
    name: '这就是数学归纳法：先说明一个盘有走法，再说明 n 个盘有走法时，怎样构造 n+1 个盘的走法。',
    next: '现在我们知道碟子继续增加也有走法。下一页再问：能不能走得更少？',
    teacher: '先请学生说明两次小塔搬运各自怎样使用已有方法，再展开核对。听他们能否解释柱子的角色变化。等起点与增加一个盘的方法都讲清楚，再介绍“数学归纳法”这个名字。此处先证明有解，随后再讨论这套方法的步数。',
  },
  en: {
    title: 'Can we always finish as we add more discs?',
    intro: 'We know three discs can be moved because we have built a route step by step. But we cannot try every disc count. Could there be a count with no route at all?',
    lead: 'Think about adding one disc twice: if you can move 2 discs, how could that route help you move 2 + 1 discs? If you can move 3 discs, how could it help you move 3 + 1 discs?',
    leadQuestion: 'What is the same in both methods? Could the same idea work as you keep adding discs?',
    diagramCaptions: ['Move the five smaller discs to B, leaving C empty', 'Move the largest disc from A to C', 'Move the five smaller discs from B to C'],
    reveal: 'Think it through, then open the proof',
    startTitle: 'Now check the starting case: one disc',
    start: 'Move one disc directly to the target. A route exists.',
    stepTitle: 'From n discs to n + 1 discs',
    setup: 'Let n be a positive integer. Suppose we have a route that moves n discs from one peg to another. Add a larger disc underneath them, making n + 1 discs.',
    steps: [
      'Use the existing method to move the n smaller discs from A to B. C remains empty.',
      'Move the largest disc from A to C.',
      'Use the existing method again to move the n smaller discs from B to C. B is now the start, A the temporary peg and C the target. The larger disc underneath on C does not obstruct the smaller discs.',
    ],
    implication: 'If n discs have a route, this construction gives a route for n + 1 discs.',
    conclusion: 'Starting with one disc, we can keep constructing a route each time we add a disc. Therefore, for every positive integer n, we can move n discs to the target peg while following the rules.',
    name: 'This is mathematical induction: establish a route for one disc, then show how a route for n discs gives a route for n + 1 discs.',
    next: 'We now know that a route exists as the number of discs grows. Next, ask whether fewer moves could work.',
    teacher: 'Ask how each smaller-tower transfer uses the existing method before opening the proof. Listen for an explanation of the changing peg roles. Introduce the name “mathematical induction” after the starting case and the extension are clear. Establish existence here, then discuss the method’s move count.',
  },
}
