// Explanations follow the structure of the puzzle before introducing notation.
export const proofCopy = {
  zh: {
    visualHelp: '需要图示？展开对照', visualNote: '图中是四个碟子，展示最大碟从 A 柱移到 C 柱的前后。先借图理清位置，再想想：换了柱名或走法，哪些理由仍然成立？',
    visualCaptions: ['最大碟移动前：小塔在 B 柱，C 柱空着。', '最大碟移动后：小塔还在 B 柱。', '最后还要把小塔搬到 C 柱，叠在最大碟上。'],
    reveal: '想好后，展开解释',
    hide: '收起推理，自己讲一遍', show: '再看推理', back: '返回', next: '这些步数真的够吗？', restart: '重新体验',
    lower: {
      eyebrow: '从图示到理由 · 把为什么讲清楚', title: '为什么不能再少？',
      intro: '刚才的演示只展示了一种走法。换一种走法，会不会更省？试着在脑中想一遍：规则究竟迫使我们做哪些事？需要时，可以展开图示对照。',
      questions: [
        { title: '最大碟第一次移动前，小碟子只能在哪里？', answer: '最大碟上面不能留有小碟子，它要去的那根柱也必须是空的。三根柱中，两根都不能放小碟子，所以小碟子必须全部叠在剩下的那根柱上。从起点走到这里，已经完整地搬过一次小塔。' },
        { title: '最大碟到了目标柱，就算完成了吗？', answer: '看它最后一次移到目标柱的那一步：它原来所在的柱上没有小碟子，目标柱也是空的。因此，小碟子此刻全部叠在第三根柱上。要完成任务，还得把这座小塔完整地搬到目标柱。最大碟此后不再移动；否则它还得回来，这一步就不是最后一次移到目标柱了。' },
        { title: '让最大碟多绕几步，能省掉前后两次搬小塔吗？', answer: '不能。第一段在最大碟第一次移动之前，第二段在它最后一次移到目标柱之后，两个时间段没有重叠。最大碟自己还至少要移动一次。中间多走的步骤可以暂时不计，但这三部分一步也不能少算。' },
      ],
      bridgeTitle: '这为什么又是一个少一个碟子的问题？',
      bridge: '只看小碟子的移动：前后两段都从一座完整的小塔开始，到另一根柱上的完整小塔结束。忽略最大碟，它们仍遵守同样的规则；小碟子放在最大碟上，也可以看作放在空柱上。因此，已经知道的小塔步数限制，在这里仍然适用。',
      connect: '把这些理由连起来',
      let: '设 n 是大于 1 的整数，表示碟子数量。',
      assumption: '如果已经说明：对于每个把 n − 1 个碟子从一根柱移到另一根柱的完整走法，至少需要 a 步；',
      consequence: '那么，刚才找出的前后两段各需至少 a 步，最大碟还至少走一步。所以，对于每个完成 n 个碟子任务的走法，至少需要：',
      counting: '1 + 2a 步',
      meaning: '这里的 2，是因为少一个碟子的完整任务出现了两次；这里的 1，是最大碟至少要走的那一步。',
      growTitle: '和式就是这样长出来的',
      start: '一个碟子从起始柱到目标柱，至少需要一步。以这一步为起点，每增加一个碟子，就把前一层已经说明的步数翻倍，再加一步。',
      barTitle: '把刚才的推理画成横线',
      barHelp: '每条横线代表一句完整的“只要……那么……”。先想想它说了什么，再点开对照。',
      barLabels: ['从一个碟子推到两个', '从两个碟子推到三个', '从三个碟子推到四个'],
      bars: ['只要已经说明搬一个碟子至少需要 1 步，那么前后各搬一次小塔、再加上最大碟的一步，就说明搬两个碟子至少需要 1 + 2 步。', '只要已经说明搬两个碟子至少需要 1 + 2 步，那么把这个步数要求翻倍再加一，就说明搬三个碟子至少需要 1 + 2 + 2² 步。', '只要已经说明搬三个碟子至少需要 1 + 2 + 2² 步，那么同一个理由就说明搬四个碟子至少需要 1 + 2 + 2² + 2³ 步。'],
      barWhy: '这些横线成立，靠的是同一个理由：前后两次完整地搬小塔，最大碟至少走一步。这个理由没有依赖某个具体的碟子数。',
      general: '设 n 是正整数。从一个碟子开始，重复这段推理 n − 1 次，就能说明：对于每个完成 n 个碟子任务的走法，至少需要下面这些步数。每次添上的一项，都来自“小塔任务出现两次”这一结构。',
      sumNote: '这个和有 n 项，第一项是 1，之后每项是前一项的两倍。一个碟子对应的和就是 1。',
      pending: '这说明不能更少。至于这些步数是不是真的够，我们前面暂时没有证明，下一页再补上。',
      recallTitle: '试着用自己的话讲一遍',
      recall: '假设有人让最大碟来回移动三次，还声称找到了一条更短的走法。你怎样只凭规则说明，前后那两次搬小塔仍然省不掉？再解释：碟子多一个，为什么步数限制就要翻倍再加一？',
      teacher: '先借演示让学生发现结构，再让他们解释规则为什么迫使这些步骤出现。学生可以看图，有把握后再尝试收起图解释。听到“图里就是这样”还不够：请追问另一种走法、最大碟绕路、柱子换名以后，理由是否仍成立。学生能解释两次小塔任务的来源，再写算式。需要帮助时可返回演示，理解后再尝试用自己的话重说一次。',
    },
    can: {
      eyebrow: '回头补上 · 这些步数确实够用', title: '凭什么说做得到？',
      intro: '前面我们暂时搁置了一个问题：已经说明不能更少，可是，用这些步数真的能完成吗？现在来补上这部分。可以借助图示，也可以在脑中回想：怎样把一套已经会用的走法接着用下去？',
      setupTitle: '已经会搬小塔，怎样接着搬大塔？',
      setup: '设 n 是大于 1 的整数。假设已经有一套搬 n − 1 个碟子的走法，设 a 是这套走法的步数。三根柱的名字不影响移动规则；换一下起始柱、临时柱和目标柱的角色，这套方法仍能用，步数也不变。',
      questions: [
        { title: '先怎样把最大碟露出来？', answer: '把已经会用的小塔走法用于 A 柱到 B 柱，C 柱作临时柱。a 步以后，小碟子全部到了 B 柱，最大碟露了出来，C 柱也空了。' },
        { title: '接下来，最大碟能去哪里？', answer: '把最大碟从 A 柱移到 C 柱，只需一步。C 柱原来是空的，这一步符合规则。' },
        { title: '最后为什么还能用同一套方法？', answer: '现在搬的是 B 柱上的同一座小塔。把 B 柱看作起始柱、A 柱看作临时柱、C 柱看作目标柱，再用一次那套走法，仍需 a 步。C 柱底下虽然有最大碟，但它比每个小碟子都大，不会妨碍小碟子的移动。' },
      ],
      countTitle: '这一次，我们真正拼出了一条走法',
      count: '前一次搬小塔用 a 步，移动最大碟用一步，再搬小塔用 a 步。每一步都能照着完成，总共就是 1 + 2a 步。',
      growTitle: '从一步开始，方法和步数一起长出来',
      start: '一个碟子直接移到目标柱，一步就能完成。每增加一个碟子，把前一套方法用两次，中间加上移动最大碟的那一步。',
      barTitle: '同样用横线表示“为什么能接着做”',
      barHelp: '每条横线代表一次完整的推断。点开看看：已有的方法，怎样变成多一个碟子的方法？',
      barLabels: ['从一个碟子构造两个', '从两个碟子构造三个', '从三个碟子构造四个'],
      bars: ['只要能用 1 步搬好一个碟子，把这个方法用两次，中间移动一次最大碟，就能用 1 + 2 步搬好两个碟子。', '只要能用 1 + 2 步搬好两个碟子，把这套方法用两次，中间移动一次最大碟，就能用 1 + 2 + 2² 步搬好三个碟子。', '只要能用 1 + 2 + 2² 步搬好三个碟子，同样的构造就能用 1 + 2 + 2² + 2³ 步搬好四个碟子。'],
      barWhy: '每条横线背后都有同一个可执行的构造：先用小塔方法，再移动最大碟，再用一次小塔方法。',
      general: '设 n 是正整数。从一个碟子的走法开始，重复这个构造 n − 1 次，就得到了 n 个碟子的完整走法。因此，对于每个正整数 n，都确实能用这个 n 项和所表示的步数完成。',
      doneTitle: '两部分合起来，才知道这是最少步数',
      done: '前一页说明：更少的步数不够。这一页说明：这些步数确实够用。',
      recallTitle: '在脑中把方法接起来',
      recall: '把目标改成 B 柱，你还会搬吗？试着说明三根柱的角色怎样换，需要时可以看图。再说清楚：我们先假设会搬的是几个碟子？这个方法用了两次以后，为什么就能多搬一个？',
      teacher: '请学生先口头构造，再对照说明。重点听他们是否能解释柱子角色的变化、底下的最大碟为什么不妨碍小碟，以及方法为什么能从一个碟子逐层建立。这段推理本身就是归纳证明的核心；等学生讲清楚以后，再命名为“数学归纳法”。',
    },
  },
  en: {
    visualHelp: 'Need a diagram? Open a reference', visualNote: 'These four-disc pictures show the largest disc moving from A to C. Use them to locate the discs, then consider which reasons still hold with different peg names or a different route.',
    visualCaptions: ['Before the largest disc moves: the smaller tower is on B and C is empty.', 'After the largest disc moves: the smaller tower is still on B.', 'The smaller tower must still reach C, on top of the largest disc.'],
    reveal: 'Explain it first, then compare', hide: 'Hide the reasoning and explain it yourself', show: 'Show the reasoning again', back: 'Back', next: 'Can these moves actually be achieved?', restart: 'Restart experience',
    lower: {
      eyebrow: 'FROM THE PICTURE TO THE REASON', title: 'Why can no route use fewer moves?',
      intro: 'The demonstration showed one route. Could a different route do better? Try to work through what the rules force us to do in your mind. Open the reference diagrams if you need support.',
      questions: [
        { title: 'Where must the smaller discs be before the largest disc first moves?', answer: 'No smaller disc can remain on top of it, and the peg it moves to must be empty. That leaves just the third peg for every smaller disc. They must form a complete smaller tower there. Reaching this point has already required a full smaller-tower transfer.' },
        { title: 'Is the task finished once the largest disc reaches the target?', answer: 'Consider its final move onto the target. Its previous peg has no smaller discs, and the target is empty. The smaller discs therefore form a complete tower on the third peg. That tower must still be transferred to the target. The largest disc does not move again: otherwise it would need to return, contradicting this being its final arrival.' },
        { title: 'Could extra moves of the largest disc avoid either smaller transfer?', answer: 'No. One transfer precedes its first move; the other follows its final move onto the target. These intervals do not overlap. The largest disc must also move at least once. We may leave additional moves uncounted, but these three contributions remain necessary.' },
      ],
      bridgeTitle: 'Why is this the same problem with one fewer disc?',
      bridge: 'Focus on the smaller discs. Each interval transfers a complete smaller tower between distinct pegs under the same rules. Ignoring the largest disc leaves a legal smaller-tower route: placing a smaller disc on it is equivalent to placing that disc on an empty peg. The established lower bound for the smaller task therefore still applies.',
      connect: 'Connect the reasons', let: 'Let n be an integer greater than 1, representing the number of discs.',
      assumption: 'If we have established that for every complete transfer of n − 1 discs between distinct pegs, at least a moves are needed,',
      consequence: 'then each of the two smaller transfers needs at least a moves, and the largest disc needs at least one. Thus, for every complete n-disc route, at least this many moves are needed:',
      counting: '1 + 2a moves', meaning: 'The 2 comes from meeting the smaller task twice. The 1 comes from the move the largest disc must make.',
      growTitle: 'This is where the sum comes from', start: 'One disc needs at least one move to reach a different peg. Starting there, each extra disc doubles the established lower bound and adds one.',
      barTitle: 'Represent the inference with a line', barHelp: 'Each line represents a complete “if … then …” statement. Explain it first, then open it to compare.',
      barLabels: ['From one disc to two', 'From two discs to three', 'From three discs to four'],
      bars: ['If one disc needs at least 1 move, then the two smaller transfers and the largest-disc move show that two discs need at least 1 + 2 moves.', 'If two discs need at least 1 + 2 moves, then doubling that lower bound and adding one shows that three discs need at least 1 + 2 + 2² moves.', 'If three discs need at least 1 + 2 + 2² moves, then the same reason shows that four discs need at least 1 + 2 + 2² + 2³ moves.'],
      barWhy: 'The same reason establishes each conditional: two complete smaller transfers and at least one largest-disc move. It does not depend on a particular disc count.',
      general: 'Let n be a positive integer. Starting with one disc and repeating this reasoning n − 1 times establishes the following lower bound for every complete n-disc route. Each additional term comes from encountering the smaller task twice.',
      sumNote: 'There are n terms, starting at 1 and doubling each time. For one disc, the sum is just 1.',
      pending: 'This rules out fewer moves. We set aside whether this many moves can actually be achieved; the next page returns to that question.',
      recallTitle: 'Try explaining it in your own words',
      recall: 'Someone moves the largest disc three times and claims to have a shorter route. How do the rules still force the two smaller-tower transfers? Then explain why adding a disc doubles the lower bound and adds one.',
      teacher: 'Use the demonstration to help students notice the structure, then ask why the rules force it. Students may keep the diagrams; hiding them is an optional next step. “That is what the picture shows” is insufficient. Ask about another route, detours, or renamed pegs. Write the expression after students explain the two smaller tasks. If needed, revisit the animation before trying to explain again in their own words.',
    },
    can: {
      eyebrow: 'RETURN TO THE QUESTION · ACHIEVE THE BOUND', title: 'Why believe it can be done?',
      intro: 'Earlier, we set aside a question: fewer moves cannot work, but can this many moves actually be achieved? We now return to it. Use the diagrams or work mentally to explain how a method we already have can be used again.',
      setupTitle: 'How does knowing a smaller-tower method help?',
      setup: 'Let n be an integer greater than 1. Suppose we have a method for transferring n − 1 discs, and let a be its move count. Peg names do not affect the rules. Reassigning the start, temporary and target roles gives the same method with the same move count.',
      questions: [
        { title: 'How can we expose the largest disc?', answer: 'Apply the smaller-tower method from A to B, using C as the temporary peg. After a moves, every smaller disc is on B. The largest disc is exposed and C is empty.' },
        { title: 'Where can the largest disc go next?', answer: 'Move it directly from A to C in one move. C was empty, so this move is legal.' },
        { title: 'Why does the same method still work at the end?', answer: 'The same smaller tower is now on B. Make B the start, A the temporary peg, and C the target. Apply the method again in a moves. The largest disc on C is larger than each smaller disc, so it does not obstruct any move of the smaller tower.' },
      ],
      countTitle: 'We have now assembled an actual route', count: 'The first smaller transfer uses a moves, the largest disc uses one, and the second smaller transfer uses a moves. Each move can be carried out: the total is 1 + 2a.',
      growTitle: 'The method and the sum grow together', start: 'One disc can reach its target directly in one move. For each extra disc, use the previous method twice, with one largest-disc move between the two uses.',
      barTitle: 'Use a line to represent why the construction continues', barHelp: 'Each line represents a complete inference. Open it to see how an existing method produces a method for one more disc.',
      barLabels: ['Construct two discs from one', 'Construct three discs from two', 'Construct four discs from three'],
      bars: ['If one disc can be transferred in 1 move, using that method twice around one largest-disc move gives a two-disc route using 1 + 2 moves.', 'If two discs can be transferred in 1 + 2 moves, using that method twice around one largest-disc move gives a three-disc route using 1 + 2 + 2² moves.', 'If three discs can be transferred in 1 + 2 + 2² moves, the same construction gives a four-disc route using 1 + 2 + 2² + 2³ moves.'],
      barWhy: 'Each conditional is supported by the same executable construction: use the smaller method, move the largest disc, and use the smaller method again.',
      general: 'Let n be a positive integer. Starting with the one-disc method and repeating this construction n − 1 times produces a complete n-disc route. So for every positive integer n, the move count represented by this n-term sum is achievable.',
      doneTitle: 'Both parts together establish the minimum', done: 'The previous page showed that fewer moves are insufficient. This page shows that this many moves are sufficient.',
      recallTitle: 'Connect the method in your mind',
      recall: 'Could you finish on B instead? Explain how the peg roles change, using the diagrams if helpful. How many discs did we suppose we could already transfer? Why does using that method twice let us transfer one more?',
      teacher: 'Ask students to construct the route aloud before comparing explanations. Listen for peg-role changes, why the largest disc does not obstruct smaller moves, and how the method can be built from one disc onwards. This reasoning is the core of the induction proof. Name mathematical induction after students can explain it.',
    },
  },
}
