export const shortestCopy = {
  zh: {
    title: '还能更少吗？',
    intro: '先看移动最大碟需要什么，再从一个碟子开始，一层层想下去。',
    question: '最大碟准备离开起始柱。上面的小碟子该怎样放？',
    choices: { some: '分开放在另外两根柱上', all: '全部叠在同一根柱上' },
    think: '选好后，试着解释：为什么另一种放法行不通？',
    retry: '再想想：小碟子这样放好以后，最大碟能移到哪根柱上？',
    reveal: '展开理由和图示',
    reasons: [
      '要移动最大碟，先得把它上面的小碟子全部移开。',
      '最大碟也不能放在小碟子上，所以它要去的那根柱必须空着。小碟子既不能留在起始柱，也不能占着这根空柱，就只能全部叠在剩下的那根柱上。',
    ],
    diagramNote: '下面用五个圆盘说明：上面四个盘先搬到 B，最大盘才能移到 C；之后，还得把这四个盘搬到 C。',
    captions: ['先把上面四个盘搬到 B，留出 C', '把最大盘从 A 移到 C', '再把四个小盘从 B 搬到 C'],
    constructionNote: '图中画出了四个小盘搬好后的位置。怎样用最少的步数完成这两次搬运，我们还没有构造出具体走法。这个问题先留到后面的“为何做得到？”再补上。',
    teacherLabel: '从规则一步步推出步数',
    practiceTitle: '分别想清每个圆盘至少要动几次',
    answerLabel: '展开答案与理由',
    practice: [
      {
        title: '两个圆盘，至少要移动几步？',
        prompt: '小圆盘要先让大圆盘动起来，最后又要叠回它上面。小圆盘至少得动几次？大圆盘呢？',
        reasons: [
          '大圆盘要动，小圆盘必须先从它上面移开，至少一次。',
          '最后，小圆盘还要叠回大圆盘上，所以它至少还得移动一次。大圆盘自己也至少得移动一次。',
          '分别看这两个盘：大圆盘至少动一次，小圆盘至少动两次。合起来至少三步，换一种走法也省不掉。',
        ],
        count: '至少（1 + 2）步，即 3 步',
      },
      {
        title: '三个圆盘，至少要移动几步？',
        prompt: '还是分别看大、中、小三个盘。用刚才对两个圆盘的理由，说明它们各自至少要动几次。',
        reasons: [
          '最大盘第一次移动前，上面两个盘必须先完整地搬到另一根柱上。最大盘最后一次到达目标柱后，这两个盘又必须完整地搬到目标柱。因此，上面这座两盘塔前后要搬两遍。',
          '看中盘：它在这座两盘塔中是大盘，搬一遍至少动一次；前后各搬一遍，就至少动两次。',
          '看最小盘：它在这座两盘塔中是小盘，搬一遍至少动两次；前后各搬一遍，就至少动四次。',
          '最大盘自己至少动一次。把每个盘的次数加起来，就是至少一步、两步、四步，合计七步。',
        ],
        count: '至少（1 + 2 + 2²）步，即 7 步',
      },
    ],
    teacher: '先让学生解释最大碟为什么能移动，再展开理由与图示。随后从一个碟子开始，让学生把刚刚说明的步数用到两个、三个碟子上。重点听他们能否说清前后两次搬小塔，而不只是选对选项或报出数字。',
    back: '返回', next: '拆解步骤', waiting: '等待教师放行',
  },
  en: {
    title: 'Could fewer moves work?',
    intro: 'First explain what lets the largest disc move. Then build the reasoning from one disc onwards.',
    question: 'The largest disc is about to leave its starting peg. How must the smaller discs be arranged?',
    choices: { some: 'Spread across the other two pegs', all: 'Stacked together on one peg' },
    think: 'After choosing, explain why the other arrangement would not work.',
    retry: 'With the smaller discs arranged that way, which peg could receive the largest disc?',
    reveal: 'Show the reasoning and diagrams',
    reasons: [
      'Before the largest disc can move, every smaller disc above it must be moved away.',
      'The largest disc cannot be placed on a smaller disc, so the peg receiving it must also be empty. The smaller discs can occupy neither the starting peg nor that empty peg. They must therefore be stacked together on the remaining peg.',
    ],
    diagramNote: 'These pictures use five discs: the four smaller discs move to B so that the largest can move to C; those four discs must then move to C.',
    captions: ['Move the four smaller discs to B, leaving C empty', 'Move the largest disc from A to C', 'Move the four smaller discs from B to C'],
    constructionNote: 'The pictures show where the four smaller discs end up, but we have not yet constructed the individual moves that complete each transfer in the fewest steps. We will return to this question in “WHY CAN?”.',
    teacherLabel: 'BUILD THE COUNT FROM THE RULES',
    practiceTitle: 'Reason through the moves each disc must make',
    answerLabel: 'Show the answer and reasoning',
    practice: [
      {
        title: 'How many moves must two discs take?',
        prompt: 'The smaller disc must let the larger disc move and finish on top of it again. How often must each disc move?',
        reasons: [
          'The smaller disc must first move off the larger one so that the larger disc can move. That requires at least one move.',
          'The smaller disc must finish on top of the larger one again, so it must move at least once more. The larger disc itself must also move at least once.',
          'The smaller disc contributes at least two moves and the larger disc at least one. Two discs therefore need at least three moves. A different route cannot avoid these movements.',
        ],
        count: 'At least (1 + 2) moves, that is, 3 moves',
      },
      {
        title: 'How many moves must three discs take?',
        prompt: 'Consider the large, middle and small discs separately. Use the two-disc reasoning to explain how often each must move.',
        reasons: [
          'Before the largest disc first moves, the complete two-disc tower must reach another peg. After the largest disc’s final arrival on the target, that two-disc tower must still reach the target. These are two separate complete transfers.',
          'The middle disc is the larger disc within that two-disc tower. It must move at least once per transfer, so at least twice in total.',
          'The smallest disc is the smaller disc within that tower. It must move at least twice per transfer, so at least four times in total.',
          'The largest disc itself moves at least once. Add the individual requirements: one, two and four moves give at least seven in total.',
        ],
        count: 'At least (1 + 2 + 2²) moves, that is, 7 moves',
      },
    ],
    teacher: 'Ask students to explain what lets the largest disc move before opening the reasoning and diagrams. Then start with one disc and ask them to use each established bound for two discs and then three. Listen for why the two smaller transfers are needed, rather than just a correct selection or a number.',
    back: 'Back', next: 'Explore the steps', waiting: 'Waiting for teacher',
  },
}
