export const shortestCopy = {
  zh: {
    title: '还能更少吗？',
    intro: '上一页已经说明：继续加盘也有走法。现在换一个问题：能不能走得更少？先看移动最大碟前必须发生什么。',
    question: '最大碟准备离开起始柱。上面的小碟子该怎样放？',
    choices: { some: '分开放在另外两根柱上', all: '全部叠在同一根柱上' },
    think: '选好后，试着解释：为什么另一种放法行不通？',
    retry: '再想想：小碟子这样放好以后，最大碟能移到哪根柱上？',
    correct: '答对了：最大碟移动前，小碟子必须全部叠在另一根柱上。',
    reveal: '展开理由和图示',
    reasons: [
      '要移动最大碟，先得把它上面的小碟子全部移开。',
      '最大碟也不能放在小碟子上，所以它要去的那根柱必须空着。小碟子既不能留在起始柱，也不能占着这根空柱，就只能全部叠在剩下的那根柱上。',
    ],
    captions: ['把最大盘上面的小塔从 A 搬到 B，留出 C', '把最大盘从 A 移到 C', '再把这座小塔从 B 搬到 C'],
    teacherLabel: '从规则一步步推出步数',
    practiceTitle: '把刚才的理由用到两个、三个盘上',
    answerLabel: '展开答案与理由',
    practice: [
      {
        title: '两个圆盘，至少要移动几步？',
        prompt: '小圆盘要先让大圆盘动起来，最后又要叠回它上面。小圆盘至少得动几次？大圆盘呢？',
        reasons: [
          '大圆盘要动，小圆盘必须先从它上面移开，至少一次。',
          '最后，小圆盘还要叠回大圆盘上，所以它至少还得移动一次。大圆盘自己也至少得移动一次。',
          '分别看这两个盘：大圆盘至少动一次，小圆盘至少动两次。合起来至少三步，换一种走法也省不掉。',
        ],
        count: '至少（1 + 2）步，即 3 步',
      },
      {
        title: '三个圆盘，至少要移动几步？',
        prompt: '根据图示中的同一个理由，上面的两盘塔要搬几遍？',
        reasons: [
          '根据图示中的同一个理由，移动最大盘之前和它最后到达目标柱之后，上面的两盘塔各要完整搬一次。最大盘自己至少移动一步。搬一次两盘塔至少要（1 + 2）步，所以三个盘至少要走：',
        ],
        count: '（1 + 2(1 + 2)）步，即 7 步',
      },
    ],
    teacher: '先让学生解释最大碟为什么能移动，再展开理由与图示。随后从一个碟子开始，让学生把刚刚说明的步数用到两个、三个碟子上。重点听他们能否说清前后两次搬小塔，而不只是选对选项或报出数字。',
    closingQuestion: '我们已经说明：少于这些步不可能。怎样确认恰好用这些步完成的走法确实存在？',
    appendixLink: '附录：为什么确实有走法达到这些步数？',
    appendixLocked: '答对本页问题并获得教师放行后可查看。',
    answerFirst: '答对本页问题后可查看。',
    back: '返回', next: '拆解步骤', waiting: '等待教师放行',
  },
  en: {
    title: 'Could fewer moves work?',
    intro: 'The previous page established a route as more discs are added. Now ask whether fewer moves could work. Start with what must happen before the largest disc moves.',
    question: 'The largest disc is about to leave its starting peg. How must the smaller discs be arranged?',
    choices: { some: 'Spread across the other two pegs', all: 'Stacked together on one peg' },
    think: 'After choosing, explain why the other arrangement would not work.',
    retry: 'With the smaller discs arranged that way, which peg could receive the largest disc?',
    correct: 'Correct: before the largest disc moves, all smaller discs must be stacked on the other peg.',
    reveal: 'Show the reasoning and diagrams',
    reasons: [
      'Before the largest disc can move, every smaller disc above it must be moved away.',
      'The largest disc cannot be placed on a smaller disc, so the peg receiving it must also be empty. The smaller discs can occupy neither the starting peg nor that empty peg. They must therefore be stacked together on the remaining peg.',
    ],
    captions: ['Move the smaller tower from A to B, leaving C empty', 'Move the largest disc from A to C', 'Move the tower from B to C'],
    teacherLabel: 'BUILD THE COUNT FROM THE RULES',
    practiceTitle: 'Use the same reasoning for two and three discs',
    answerLabel: 'Show the answer and reasoning',
    practice: [
      {
        title: 'How many moves must two discs take?',
        prompt: 'The smaller disc must let the larger disc move and finish on top of it again. How often must each disc move?',
        reasons: [
          'The smaller disc must first move off the larger one so that the larger disc can move. That requires at least one move.',
          'The smaller disc must finish on top of the larger one again, so it must move at least once more. The larger disc itself must also move at least once.',
          'The smaller disc contributes at least two moves and the larger disc at least one. Two discs therefore need at least three moves. A different route cannot avoid these movements.',
        ],
        count: 'At least (1 + 2) moves, that is, 3 moves',
      },
      {
        title: 'How many moves must three discs take?',
        prompt: 'Using the same reasoning as in the diagrams, how many times must the two-disc tower be transferred?',
        reasons: [
          'For the same reason shown in the diagrams, the two-disc tower must be transferred completely before the largest disc first moves and again after its final arrival on the target. The largest disc itself moves at least once. Each two-disc transfer needs at least (1 + 2) moves, so three discs need at least:',
        ],
        count: '(1 + 2(1 + 2)) moves, that is, 7 moves',
      },
    ],
    teacher: 'Ask students to explain what lets the largest disc move before opening the reasoning and diagrams. Then start with one disc and ask them to use each established bound for two discs and then three. Listen for why the two smaller transfers are needed, rather than just a correct selection or a number.',
    closingQuestion: 'We have shown that fewer moves are impossible. How can we be sure there is a route that finishes in exactly this many moves?',
    appendixLink: 'Appendix: why does a route achieving this bound exist?',
    appendixLocked: 'Available after a correct answer and teacher approval.',
    answerFirst: 'Available after a correct answer on this page.',
    back: 'Back', next: 'Explore the steps', waiting: 'Waiting for teacher',
  },
}
