// Chinese classroom copy. Keys are the original English UI text, not stored data.
export const zh = {
  "Still to explain": "还要说明",
  "A completed route does not by itself establish the minimum.": "找到一条走法，还不能据此断定它的步数最少。",
  "Start with the rules, before counting. To move the largest disc, what must happen to the discs above it and to the peg it moves to?": "先不计算，想想规则：要移动最大碟，上面的小碟子怎么办？它要去的那根柱上能有碟子吗？",
  "Could a different route avoid moving the smaller tower out of the way?": "换一种走法，能不能省掉先把上面的小塔搬走这件事？",
  "The largest disc must be uncovered, and the peg it moves to must be empty. So every smaller disc must be on the third peg. Explain why moving just some of them would not work.": "最大碟上面不能有碟子，它要去的那根柱也必须是空的。所以，小碟子必须全部叠在第三根柱上。试着解释：只搬走一部分为什么不行？",
  "Ask students to explain both constraints: the largest disc must be uncovered and its destination must be empty. Choosing “all” alone is not yet an explanation. Use the next demonstration to connect these constraints to the repeated smaller task.": "请学生解释两个条件：最大碟上面不能有碟子，它要去的柱也必须是空的。选对“全部”还不够，要听他们说出理由。接下来的演示用来帮助学生发现：为什么会遇到两次搬小塔的问题。",
  "What must be done around the largest-disc move?": "最大碟移动前后，要做哪些事？",
  "The pictures use four discs. Look at the smaller tower before and after the largest disc moves to C. We will count the moves in the next activity.": "图中以四个碟子为例。看看最大碟移到 C 柱前后，小塔在哪里、还要搬到哪里。下一步再用演示数一数。",
  "Move the smaller tower aside": "先把上面的小塔搬到 B 柱",
  "Move the smaller tower onto the largest disc": "再把小塔搬到 C 柱，叠在最大碟上",
  "Why does the same smaller task appear twice?": "为什么前后两次遇到的是同一个搬小塔的问题？",
  'Induction Lab': '数学归纳实验室',
  'PLAY': '动手试试', 'NOTICE': '想一想', 'SHORTEST?': '还能更少吗？', 'STEPS': '拆解步骤', 'PROVE': '说明理由', 'WHY CAN?': '为何做得到？',
  'Playing': '操作中', 'Noticing': '思考中', 'Shortest?': '还能更少吗？', 'Steps': '拆解步骤', 'Prove': '说明理由',
  'Activity sequence': '活动流程', 'Skip to activity': '跳到活动内容',
  'Leave': '退出课堂', 'Classroom': '进入课堂', 'Teacher lens': '教学提示', 'TEACHER LENS': '教学提示',
  'Facilitator cue': '主持提示', 'FACILITATOR ·': '主持提示 ·', 'THINK · 20 SECONDS': '思考 20 秒', 'EXPLAIN THE GENERAL CASE': '讲解一般情形',
  'Move the tower.': '先试着搬完，', 'Then prove your best.': '再想能否更少。',
  'Move the tower from A to C in as few moves as possible. Move one disc at a time. Never place a larger disc on a smaller one.': '把整座塔从 A 柱移到 C 柱，步数越少越好。每次只能移动一个碟子，大碟子不能压在小碟子上。',
  'DISCS': '碟子数量', 'Number of discs': '选择碟子数量', 'MOVES': '当前步数', 'MINIMUM': '最少步数', 'Move count and minimum': '当前步数与最少步数', 'Move count': '当前步数',
  'What must happen before the largest disc can move?': '要移动最大的碟子，必须先做什么？',
  'Undo': '撤销一步', 'Reset': '重新开始', 'Next demonstration move': '演示下一步', 'Hint for this position': '提示下一步',
  'Facilitator controls': '演示控制', 'First volunteer: a non-Science teacher, two discs.': '先请一位非理科教师尝试两个碟子。', 'Second volunteer: a mathematics teacher, three discs.': '再请一位数学教师尝试三个碟子。', 'Try another tower size.': '换一个碟子数量试试。', 'Aim for the fewest moves.': '尽量用最少的步数完成。',
  'A shorter route is possible. Show it after this attempt.': '这次还可以少走几步。请在尝试结束后展示最短路线。',
  'Reveal minimum': '揭晓最少步数', 'Show shortest route from start': '从头演示最短路线',
  'Start with two discs, then select three for the second volunteer. Keep the minimum hidden during each attempt. If needed, demonstrate the shortest route. Ask the observing teachers: where would you pause, and what would you ask students to explain?': '先用两个碟子，再让第二位教师尝试三个。尝试过程中不揭晓最少步数；结束后，如有需要，再演示最短路线。请台下教师思考：你会在哪里暂停？会让学生解释什么？',
  'Unknown moves plus one plus unknown moves': '未知步数，加一步，再加未知步数',
  'Next volunteer: three discs': '接下来试三个碟子', 'Set the audience task': '进入思考任务',
  'Could six moves work?': '六步能完成吗？', 'Could fewer moves work?': '还能少走几步吗？',
  'We found a seven-move route for three discs. Could six moves or fewer work?': '三个碟子，我们已经找到七步的走法。六步或更少，能完成吗？',
  'Finding a route shows it can be done. Does it show that fewer moves are impossible?': '成功搬完一次，只能说明这条走法可行。要判断它是不是最短的走法，还需要什么理由？',
  'Think of a reason beyond “I tried it”. Keep your reasoning for now.': '不能只凭“我试过了”来判断。先自己想一想，稍后再交流。',
  'complete a route first': '完成后显示步数', 'minimum proved': '最少需要多少步？',
  'Give teachers 20 seconds to think, then park the answer. Switch to the teacher role: “A student says, ‘I tried lots of times, so this is the minimum.’ What would you ask next?” Model a pause before the largest disc moves, then revisit their reasoning.': '给台下教师 20 秒思考，先不公布理由。接着切换到教师角色：“学生说，我试了很多次，所以这就是最少步数。你会怎样追问？”示范在最大碟移动前暂停，再回过头讨论他们的理由。',
  'Back to play': '返回操作', 'THINK FIRST': '先想一想', 'ROUTE FOUND': '已找到一种走法',
  'What does a completed route establish?': '成功搬完一次，能得出哪个结论？', 'What has been proved': '选择这次操作能够说明的结论',
  'It can be done in that many moves.': '用这么多步，确实可以完成。', 'This establishes what is possible.': '这条走法已经说明：这些步数足够了。',
  'It cannot be done faster.': '不可能用更少的步数完成。', 'This would require a lower bound.': '要得到这个结论，还需要说明为什么不能更少。',
  'Not yet. One route cannot rule out every shorter route.': '还不能这样判断。找到一种走法，并没有排除步数更少的走法。',
  'Exactly.': '对。', 'Now look for a cost that every legal solution must pay.': '接下来想一想：不论怎样走，有哪些步骤都省不掉？',
  'Open SHORTEST?': '看看能否更少', 'Waiting for teacher': '等待教师放行',
  'Let n > 1 be the number of discs. M(n) is the minimum number of moves to transfer the tower between two pegs.': '设 n 是大于 1 的整数，表示碟子数量。M(n) 表示把整座塔从一根柱移到另一根柱所需的最少步数。',
  'MUST': '哪些步骤省不掉？', 'Show every legal solution must pay a cost. This creates a lower bound.': '先找出不论怎样走都省不掉的步骤，再判断至少需要多少步。',
  'Before the largest disc moves,': '移动最大碟之前，', 'smaller discs must be together on the other peg.': '小碟子必须集中到另一根柱上。', 'some': '部分', 'all': '全部',
  'Some is not enough—the largest disc stays trapped.': '只移开一部分还不够，最大碟仍然被压着。',
  "Before the largest disc's first move: at least M(n − 1) moves. After its last move to C: at least M(n − 1) more. The largest disc moves at least once.": '最大碟第一次移动前，至少要走 M(n − 1) 步；最后一次移到 C 柱后，至少还要走 M(n − 1) 步。最大碟本身至少移动一次。',
  'A route with smaller-transfer counts a and b takes a + 1 + b moves. It need not be shortest. For the lower bound, use the first and last moves of the largest disc, so the argument also covers routes that move it more than once. Ask teachers which student explanation would show understanding.': '如果前后两次搬小塔分别用了 a 步和 b 步，整条路线就用了 a + 1 + b 步，但它未必最短。论证下界时，要看最大碟的第一次移动和最后一次移到目标柱，才能涵盖最大碟来回移动的走法。请教师说说：学生怎样解释，才算理解了？',
  'Back': '返回', 'Explore the steps': '进入步骤演示', 'A route for n > 1 discs': '先看最大碟前后的两件事',
  'A: start · B: temporary peg · C: target. Clear C before moving the largest disc there.': 'A 是起始柱，B 是临时柱，C 是目标柱。最大碟移到 C 柱前，C 柱必须清空。',
  'move n − 1 smaller to B': '把 n − 1 个小碟移到 B 柱', 'move largest': '移动最大碟', 'move n − 1 smaller to C': '把 n − 1 个小碟移到 C 柱',
  'M of n minus one, plus one, plus M of n minus one': 'M(n − 1) 加 1，再加 M(n − 1)',
  'This page is unavailable.': '这个页面暂时无法打开。',
  'Answer the NOTICE question correctly first.': '请先答对“想一想”中的问题。',
  'Waiting to confirm classroom approval. Check your connection.': '正在确认教师是否已放行，请检查网络连接。',
  'Your teacher needs to start the guided sequence for this class.': '请教师先为这节课启用分步放行。',
  'Your answer is correct. Waiting for your teacher to open SHORTEST? for the class.': '你已答对。请等待教师为全班开放“还能更少吗？”。',
  'Answer the SHORTEST? question correctly first.': '请先答对“还能更少吗？”中的问题。',
  'Your answer is correct. Waiting for your teacher to open STEPS for the class.': '你已答对。请等待教师为全班开放“拆解步骤”。',
  'Select the top disc, then choose a destination peg.': '先选中最上面的碟子，再选择要移到的柱子。',
  'That move is not legal: a larger disc cannot sit on a smaller one.': '这一步不符合规则：大碟子不能放在小碟子上。',
  'Last move undone.': '已撤销上一步。', 'The tower is already complete.': '已经搬完了。',
  'Shortest route from the starting position. Advance one move at a time and pause before the largest disc moves.': '现在从起点演示最短路线。每次前进一步，在最大碟移动前暂停。',
  'Pause before moving the largest disc. Where is the smaller tower, and why must the target peg be empty?': '先停在最大碟移动之前。小塔在哪里？目标柱为什么必须清空？',
  'The largest disc is on the target peg. Which smaller problem must now be solved again?': '最大碟已经到了目标柱。接下来又要解决哪个较小的搬塔问题？',
  'That move is not legal. Move one top disc onto an empty peg or a larger disc.': '这一步不符合规则。只能移动最上面的碟子，并把它放到空柱或更大的碟子上。',
  'First, move the smaller tower': '先把上面的小塔移开',
  'Predict where the smaller tower must go before the largest disc can move directly to C.': '先预测一下：最大碟要直接移到 C 柱，上面的小塔必须先搬到哪里？',
  'Start with one disc': '从一个碟子开始', 'One legal move transfers the disc from A to C. No smaller tower is needed.': '从 A 柱移到 C 柱，一步就够。这时没有需要先搬走的小塔。',
  'Pause before the largest disc': '最大碟移动前，先停一下', 'The smaller tower is on B. Why must C be empty before the largest disc moves there?': '小塔已经到了 B 柱。最大碟移过去之前，C 柱为什么必须是空的？',
  'Pause after the largest disc': '最大碟到位后，再停一下', 'The largest disc is on C. Which smaller task appears again, and which peg is temporary now?': '最大碟已经到了 C 柱。接下来又要搬哪座小塔？这次从哪根柱出发，搬到哪里，借助哪根柱？',
  'Transfer the smaller tower again': '再搬一次小塔', 'The smaller tower moves from B to C, using A as its temporary peg.': '这次把小塔从 B 柱搬到 C 柱，A 柱变成了临时柱。',
  'The construction is complete': '演示结束', 'One disc reaches its target in one move. This initial case starts the construction.': '一个碟子，一步到位。这就是整个构造的起点。',
  'Point to the one largest-disc move and the two smaller transfers. How does the sum count them?': '先试着不看动画，说清楚：最大碟移动前，必须先完成什么？最大碟到位后，为什么又回到了搬同一座小塔的问题？',
  'Your route is complete': '你已经搬完了', 'You are exploring a different route': '你正在尝试另一种走法',
  'The sum below counts the walkthrough, not this route. Select Restart walkthrough to return to that construction.': '下面的和式计算的是演示路线的步数。你现在的走法与演示不同；点击“重看演示”，可以回到演示起点。',
  'STEPS · BUILD THE PATTERN': '拆解步骤 · 看见重复的小任务', 'Pause. Predict.': '停一停，猜下一步，', 'Explain.': '再说说为什么。',
  'Explore one to four discs. Follow a construction from A to C and watch the smaller task appear twice.': '试试一至四个碟子。跟着演示从 A 柱搬到 C 柱，观察同一个较小任务怎样出现两次。',
  'Walkthrough disc count': '演示碟子数量', 'Complete': '已完成', 'Paused': '已暂停', 'Walkthrough controls': '步骤演示控制',
  'Next move': '下一步', 'Pause': '暂停', 'Play': '播放', 'Restart walkthrough': '重看演示',
  'Reduced motion is on. Use Next move to advance at your pace.': '已按你的系统设置减少动画。点击“下一步”，按自己的节奏观看。',
  'Play pauses before and after the largest-disc move, then at the finish. You can also move the discs yourself.': '播放会在最大碟移动前、移动后和完成时自动暂停。你也可以自己移动碟子。',
  'With four discs, pause after moves 7 and 8. Ask students to explain the changing peg roles before continuing. Then ask the observing teachers: which answer would show that a student understands the repeated smaller task?': '演示四个碟子时，在第 7 步和第 8 步后暂停。让学生借助画面解释：小塔从哪里搬到哪里，三根柱的角色怎样变化？理解后，可以尝试不看屏幕重说一次。请台下教师判断：怎样的回答说明学生理解了两次搬小塔为何是同一个问题？',
  'YOUR EXPLORATION': '你的尝试', 'WATCH THE SMALLER TASK': '留意小塔的搬运', 'PAUSE & EXPLAIN': '停下来，说说理由',
  'Moves in the construction': '这套走法的步数', 'MOVES IN THIS CONSTRUCTION': '这套走法用了多少步',
  'The initial case: one disc, one move.': '初始情形：一个碟子，一步完成。',
  'PROVE: rule out fewer': '证明为什么不能更少',
  'From the smaller case to the next case': '从较小情形推到下一情形', 'IF': '如果', 'THEN': '那么',
  'PROVE · THE LOWER BOUND': '证明下界 · 说明为什么不能更少', 'Why no shorter route works': '为什么不可能更少？',
  'For every legal transfer of n discs between distinct pegs, prove that at least this many moves are needed:': '对于每个把 n 个碟子从一根柱搬到另一根柱的完整解法，只要符合规则，就至少需要下面这么多步：',
  'INITIAL CASE': '初始情形', 'One disc requires at least one move.': '一个碟子要换到另一根柱，至少得走一步。',
  'The inference for n > 1': '为什么少一个碟子的结论能用在这里？', 'Let n be an integer greater than 1. Use the smaller-case statement to justify the next case.': '设 n 是大于 1 的整数。下面用较小情形的结论，说明下一情形为什么成立。',
  'Three unavoidable costs': '这三部分的步数省不掉', 'Before the first largest-disc move': '最大碟第一次移动前',
  'The smaller tower must be transferred off the largest disc and onto the remaining peg.': '上面的小碟子必须先全部移开，叠到第三根柱上。', 'At least S(n − 1)': '至少 S(n − 1) 步',
  'The largest disc itself': '最大碟本身的移动', 'It starts away from the target and must reach it. It must move at least once.': '最大碟开始时不在目标柱上，最后必须到达那里，因此至少要移动一次。', 'At least 1': '至少 1 步',
  'After its final move onto the target': '最大碟最后一次移到目标柱后', 'The smaller tower is on the other peg. It must now be transferred onto the largest disc.': '这时小塔在另一根柱上，还得把它搬到最大碟上。',
  'ADD THE NON-OVERLAPPING COSTS': '把互不重叠的三部分加起来',
  'These costs occur in separate parts of the route. Extra moves only add to them. The initial case and this inference establish the lower bound for every integer n ≥ 1.': '这三部分发生在不同的阶段，没有重复计数。多绕的步骤只会增加总步数。结合初始情形，就能得到：对于每个整数 n ≥ 1，所需步数都不低于这个和式。',
  'WHERE WAS THE ASSUMPTION USED?': '较小情形的假设，用在了哪里？', 'Explain why each smaller-tower transfer costs at least S(n − 1), even when the route includes detours.': '即使走法中有来回绕行，为什么前后两次搬小塔仍然各需至少 S(n − 1) 步？',
  'Ask students to connect the two S(n − 1) terms to the two smaller transfers. Using the largest disc’s first move and final move onto the target keeps the argument valid even for routes that move that disc more than once. A correct formula alone does not show this understanding.': '请学生把两个 S(n − 1) 分别对应到前后两次搬小塔。这里看的是最大碟的第一次移动和最后一次移到目标柱，因此最大碟来回移动的走法也包含在内。只写对公式，还不足以说明学生理解了这层推理。',
  'Why believe CAN?': '凭什么说做得到？', 'Why believe “CAN”?': '凭什么说做得到？',
  'THE CONSTRUCTION · CLOSE THE ARGUMENT': '构造走法 · 补全证明',
  'A lower bound rules out fewer moves. We still need a route that achieves the sum for every integer n ≥ 1.': '下界说明不能更少。但还要说明：对于每个整数 n ≥ 1，确实存在一种走法，步数恰好等于这个和式。',
  'Earlier, we set aside a question: can this sum of moves actually be achieved? Now we return to it. We need a route that achieves the sum for every integer n ≥ 1.': '前面我们暂时搁置了一个问题：这个和式给出的步数，真的做得到吗？现在回过头来证明这一点：对于每个整数 n ≥ 1，都要能构造出一种走法，步数恰好等于这个和式。',
  'Transfer one disc directly to its target in one move.': '一个碟子直接移到目标柱，一步就完成。',
  'Build the next case from the smaller case': '用较小情形的走法，构造下一情形', 'Let n be an integer greater than 1. The peg names change; the rules and the smaller task stay the same.': '设 n 是大于 1 的整数。柱子的角色会变，但搬小塔的规则和任务没有变。',
  'Construct the next case with two smaller transfers': '用两次搬小塔构造下一情形',
  '1. Transfer the smaller tower': '1. 先移开上面的小塔', 'Use the smaller-case route from A to B, with C as the temporary peg.': '用较小情形的走法，把小塔从 A 柱搬到 B 柱，C 柱作临时柱。', 'S(n − 1) moves': 'S(n − 1) 步',
  '2. Move the largest disc': '2. 移动最大的碟子', 'C is empty, so the move from A to C is legal.': 'C 柱已经清空，最大碟可以从 A 柱直接移过去。', '1 move': '1 步',
  '3. Use the smaller case again': '3. 再用一次较小情形的走法', 'Transfer the smaller tower from B to C, using A. The largest disc supports each smaller disc.': '把小塔从 B 柱搬到 C 柱，这次用 A 柱作临时柱。最大碟可以承托每个小碟子，不会妨碍这套走法。',
  'The pictures show four discs; the same construction uses a smaller tower of n − 1 discs.': '图中以四个碟子为例。一般情形中的小塔由 n − 1 个碟子组成，构造方法相同。',
  'COUNT THE CONSTRUCTED ROUTE': '算一算这套走法的步数',
  'The initial case and this construction provide a legal route using S(n) moves for every integer n ≥ 1.': '结合初始情形，这个构造说明：对于每个整数 n ≥ 1，都存在一种符合规则、恰好用 S(n) 步的走法。',
  'NOW THE MINIMUM IS ESTABLISHED': '到这里，才证明了最少步数', 'No route uses fewer moves, and a route using this many moves exists.': '更少的步数做不到，而这么多步确实做得到。',
  'EXPLAIN THE INFERENCE': '把推理说清楚', 'Where did we use the smaller-case assumption twice? Why does the one-disc case start the argument?': '较小情形的假设在哪两处派上了用场？为什么一个碟子的情形能启动整个推理？',
  'Invite teachers to name a pause point, a question, and the student explanation they would listen for. For example: “How does the route you already know for the smaller tower let you construct the next case?” Link the answer to IF → THEN, rather than asking students to copy a proof template.': '请教师说出一个暂停点、一句追问，以及期待听到的学生解释。例如：“知道小塔怎样搬，怎么就能设计出多一个碟子时的走法？”让学生把“如果 → 那么”说清楚，而不只是照着模板写证明。',
  'Restart experience': '重新体验',
  'LIVE CLASSROOM': '实时课堂', 'ONE PUZZLE · MANY PATHS': '同一个问题，不同的走法', 'See mathematical thinking unfold.': '看见学生是怎样想的。',
  'Students remain pseudonymous. Teachers see milestones, not keystrokes or personal data.': '学生使用昵称或座位号参与。教师可以查看活动进度和作答情况，不记录键盘输入过程。',
  'Choose classroom role': '选择参与身份', 'STUDENT': '学生', 'Join a class': '加入课堂', 'Enter the six-character code displayed by your teacher.': '输入教师提供的六位课堂码。',
  'Class code': '课堂码', 'Continue as student': '以学生身份继续', 'TEACHER': '教师', 'Open the live board': '查看课堂进展',
  'Create class codes and watch each learner move from play to proof.': '创建课堂码，查看学生从动手尝试到解释、证明的进展。', 'Teacher dashboard': '教师看板',
  'STUDENT ENTRY': '学生入口', 'Bring your strategy.': '带着你的想法来，', 'Leave your name behind.': '用昵称就能参与。',
  'Choose an alias or seat number. The teacher sees your mathematical progress, not personal information.': '填写昵称或座位号即可。教师会看到你的操作进度和回答，不需要填写真实姓名。',
  'No email, password or account required': '无需邮箱、密码或注册账号', 'Enter the class code': '输入课堂码', 'Six-character code': '六位课堂码', 'Choose how you appear': '填写课堂中显示的名字',
  'Alias or seat number': '昵称或座位号', 'e.g. Table 4': '例如：第 4 组', 'Classroom mode is not configured in this build.': '当前网站尚未配置课堂连接，请联系教师。', 'Joining…': '正在加入…', 'Enter the induction lab': '进入课堂',
  'Classroom approval could not be checked.': '暂时无法确认教师是否已放行。', 'Opening your classroom progress…': '正在读取你的课堂进度…', 'Retry connection': '重新连接',
  'TEACHER ACCESS': '教师入口', 'Your live view of the room.': '随时了解课堂进展。', 'A secure email link keeps student progress visible only to the teacher who created the class.': '通过邮箱链接登录。学生进度仅对创建这节课的教师开放。',
  'Check your email': '请查收邮件', 'Open the Supabase sign-in link on this device to continue.': '请在这台设备上打开邮件中的 Supabase 登录链接。', 'Use another email': '换一个邮箱',
  'PASSWORDLESS SIGN-IN': '邮箱链接登录', 'Send me a secure link': '发送登录链接', 'Email address': '邮箱地址', 'Sending…': '正在发送…', 'Email sign-in link': '发送登录邮件',
  'Joined': '加入时间', 'discs': '个碟子', 'Correct ✓': '已答对 ✓', 'Needs prompt': '需要引导', 'Sign out': '退出登录', 'YOUR CLASSES': '我的课堂',
  'Class title': '课堂名称', 'Year 12 Induction': '十二年级：数学归纳法', 'Creating…': '正在创建…', '+ New live class': '+ 新建课堂', 'Live': '进行中', 'Ended': '已结束',
  'Create your first live class.': '先创建一节课堂。', 'Students will join using a short code—no accounts required.': '学生输入课堂码即可加入，无需注册账号。', 'LIVE SESSION': '课堂进行中', 'SESSION ENDED': '课堂已结束',
  'Created': '创建时间', '· Expires': '· 到期时间', 'STUDENT CODE': '学生课堂码', 'Link copied ✓': '链接已复制 ✓', 'Copy student link': '复制学生入口链接',
  'Class progress summary': '全班进度概览', 'joined': '人已加入', 'towers solved': '人已完成搬塔', 'reached PROVE': '人已进入证明', 'hints used': '次提示',
  'Class progression approvals': '全班放行控制', 'Guide the class together': '把握全班的推进节奏',
  'Your approval applies to the class. Each learner must also answer the preceding question correctly.': '点击放行会为全班开放下一阶段。每位学生仍需先答对上一阶段的问题。',
  'This class uses the earlier sequence. Enable the two approval points; learners beyond NOTICE return to NOTICE, with their saved answers kept.': '这节课仍使用旧流程。启用两次放行后，已进入后续阶段的学生会回到“想一想”，已保存的答案会保留。',
  'Enabling…': '正在启用…', 'Use guided sequence': '启用分步放行', 'NOTICE → SHORTEST?': '想一想 → 还能更少吗？', 'SHORTEST? → STEPS': '还能更少吗？ → 拆解步骤',
  'have answered NOTICE correctly.': '人已答对“想一想”。', 'have answered SHORTEST? correctly.': '人已答对“还能更少吗？”。',
  'SHORTEST? approved ✓': '“还能更少吗？”已开放 ✓', 'STEPS approved ✓': '“拆解步骤”已开放 ✓', 'Approving…': '正在放行…',
  'Approve class: SHORTEST?': '全班放行：还能更少吗？', 'Approve class: STEPS': '全班放行：拆解步骤',
  'After STEPS, learners can continue to PROVE and WHY BELIEVE CAN? without another class approval.': '“拆解步骤”开放后，学生可继续查看“说明理由”和“为何做得到？”，不需要再次放行。',
  'Learner progress': '学生进度', 'Updates appear live as each browser moves through the activity.': '学生的操作进度和作答情况会持续更新。', 'End class': '结束课堂',
  'Learner': '学生', 'Stage': '当前阶段', 'Moves': '步数', 'Hints': '提示次数', 'Waiting for students to join': '等待学生加入，课堂码：', 'Opening classroom…': '正在打开课堂…',
  'Something went wrong. Please try again.': '操作未完成，请重试。',
  'The guided classroom update needs to be applied in Supabase. Ask the project owner to run the guided sequence migration.': '课堂后台尚未更新，请联系项目管理员完成配置。',
  'Anonymous student access is not enabled in Supabase yet.': '课堂尚未开启学生免注册入口，请联系教师。',
  'The classroom database setup has not been applied yet.': '课堂后台尚未完成配置，请联系教师。',
  'The class could not be joined.': '暂时无法加入课堂，请检查课堂码后重试。',
  'Progress could not be saved for this participant.': '进度暂时未能保存，请检查网络连接。',
  'The classroom state could not be loaded.': '暂时无法读取课堂状态，请重试。',
  'A unique class code could not be created. Please try again.': '课堂码创建失败，请重试。',
  'This class has ended.': '这节课已结束。',
  'Class not found or no longer active.': '课堂不存在或已结束，请向教师确认课堂码。',
  'Failed to fetch': '网络连接失败，请检查网络后重试。', 'Invalid login credentials': '登录信息无效，请重新登录。',
  'Email rate limit exceeded': '登录邮件发送过于频繁，请稍后再试。',
  'An authenticated browser session is required.': '登录状态已失效，请重新进入课堂。',
  'This class participant is not available to the current browser.': '当前浏览器无法读取这条参与记录，请重新加入课堂。',
  'Teacher sign-in is required.': '请先以教师身份登录。',
  'Only the owner of an active class can enable this sequence.': '只有创建这节课的教师才能启用流程，且课堂必须仍在进行。',
  'Only the owner of an active class can approve progression.': '只有创建这节课的教师才能放行，且课堂必须仍在进行。',
  'Enable the guided sequence before approving progression.': '请先启用分步放行。',
  'Approve SHORTEST? before approving STEPS.': '请先开放“还能更少吗？”，再开放“拆解步骤”。',
  'Use two or three discs before the STEPS activity.': '进入“拆解步骤”前，请使用两个或三个碟子。',
  'Use one to four discs in the STEPS activity.': '“拆解步骤”支持一至四个碟子。',
  'Answer NOTICE correctly and wait for teacher approval of SHORTEST?.': '请先答对“想一想”，并等待教师开放“还能更少吗？”。',
  'Answer SHORTEST? correctly and wait for teacher approval of STEPS.': '请先答对“还能更少吗？”，并等待教师开放“拆解步骤”。',
};

export const patterns = [
  [/^Solved in (\d+) moves, matching the minimum\. Why can no shorter route work\?$/, (_, n) => `用了 ${n} 步，恰好达到最少步数。为什么不可能更少？`],
  [/^Solved in (\d+) moves\. Could fewer moves work\? Explain your reasoning\.$/, (_, n) => `你用 ${n} 步完成了。还能更少吗？说说你的理由。`],
  [/^Legal move\. (\d+) moves? so far\.$/, (_, n) => `这一步符合规则，目前共走了 ${n} 步。`],
  [/^Try moving the top disc from peg ([ABC]) to peg ([ABC])\.$/, (_, from, to) => `试着把 ${from} 柱最上面的碟子移到 ${to} 柱。`],
  [/^moves found with (\d+) discs$/, (_, n) => `本次完成步数（${n} 个碟子）`],
  [/^One largest-disc move \+ two transfers of the (\d+)-disc tower\.$/, (_, n) => `移动最大碟用 1 步，再加上前后两次搬 ${n} 个小碟子所用的步数。`],
  [/^Tower of Hanoi with (\d+) discs?$/, (_, n) => `${n} 个碟子的汉诺塔`],
  [/^Peg ([ABC])(, select as move destination)?$/, (_, peg, destination) => `${peg} 柱${destination ? '，移到这里' : ''}`],
  [/^(Select|Deselect) disc (\d+) on peg ([ABC])$/, (_, action, n, peg) => `${action === 'Select' ? '选中' : '取消选中'} ${peg} 柱上的 ${n} 号碟子`],
  [/^Move selected disc to peg ([ABC])$/, (_, peg) => `把选中的碟子移到 ${peg} 柱`],
];
